### ISSUE TITLE
Drop unused dependencies

### ISSUE THREAD

**Issue by dmyersturnbull** [rcsb/py-rcsb-api#34]
They're both requirements: in [`requirements.txt`](https://github.com/rcsb/py-rcsb-api/blob/master/requirements.txt#L2) and [read in `setup.py`](https://github.com/rcsb/py-rcsb-api/blob/master/setup.py#L18).

But [this if statement](https://github.com/rcsb/py-rcsb-api/blob/74d6de28b21e74fa631bea409acefda24649eed9/rcsbapi/data/schema.py#L75) always matches, so rustworkx is used.

Double-check me on this:
[`rustworkx` isn't used otherwise](https://github.com/search?q=repo%3Arcsb%2Fpy-rcsb-api%20rustworkx&type=code), and same with `networkx`.

**Comment by piehld** [comment]
networkx has been removed from the requirements
